// Code generated by "stringer -type=ElementType -trimprefix ElementType"; DO NOT EDIT.

package msgpack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElementTypeNil-1]
	_ = x[ElementTypeBool-2]
	_ = x[ElementTypeFloat-3]
	_ = x[ElementTypeInt-4]
	_ = x[ElementTypeUint-5]
	_ = x[ElementTypeString-6]
	_ = x[ElementTypeObject-7]
	_ = x[ElementTypeArray-8]
	_ = x[ElementTypeBin-9]
	_ = x[ElementTypeExtension-10]
}

const _ElementType_name = "NilBoolFloatIntUintStringObjectArrayBinExtension"

var _ElementType_index = [...]uint8{0, 3, 7, 12, 15, 19, 25, 31, 36, 39, 48}

func (i ElementType) String() string {
	i -= 1
	if i >= ElementType(len(_ElementType_index)-1) {
		return "ElementType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ElementType_name[_ElementType_index[i]:_ElementType_index[i+1]]
}
